// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VectorMatchEngine.Data;

#nullable disable

namespace VectorMatchEngine.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VectorMatchEngine.Data.Entities.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PreservedColumnsJson")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<int>("VectorDimensions")
                        .HasColumnType("int");

                    b.Property<string>("VectorizedColumnsJson")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("Id");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("VectorMatchEngine.Data.Entities.DatasetRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<string>("PreservedDataJson")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.Property<byte[]>("VectorData")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetRecords");
                });

            modelBuilder.Entity("VectorMatchEngine.Data.Entities.MatchJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DatasetAId")
                        .HasColumnType("int");

                    b.Property<int>("DatasetBId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Threshold")
                        .HasColumnType("float");

                    b.Property<int>("TotalMatchesFound")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatasetAId");

                    b.HasIndex("DatasetBId");

                    b.ToTable("MatchJobs");
                });

            modelBuilder.Entity("VectorMatchEngine.Data.Entities.MatchResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("MatchJobId")
                        .HasColumnType("int");

                    b.Property<long>("RecordAId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecordBId")
                        .HasColumnType("bigint");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MatchJobId");

                    b.HasIndex("RecordAId");

                    b.HasIndex("RecordBId");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("VectorMatchEngine.Data.Entities.DatasetRecord", b =>
                {
                    b.HasOne("VectorMatchEngine.Data.Entities.Dataset", "Dataset")
                        .WithMany("Records")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("VectorMatchEngine.Data.Entities.MatchJob", b =>
                {
                    b.HasOne("VectorMatchEngine.Data.Entities.Dataset", "DatasetA")
                        .WithMany()
                        .HasForeignKey("DatasetAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VectorMatchEngine.Data.Entities.Dataset", "DatasetB")
                        .WithMany()
                        .HasForeignKey("DatasetBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatasetA");

                    b.Navigation("DatasetB");
                });

            modelBuilder.Entity("VectorMatchEngine.Data.Entities.MatchResult", b =>
                {
                    b.HasOne("VectorMatchEngine.Data.Entities.MatchJob", "MatchJob")
                        .WithMany("Results")
                        .HasForeignKey("MatchJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VectorMatchEngine.Data.Entities.DatasetRecord", "RecordA")
                        .WithMany()
                        .HasForeignKey("RecordAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VectorMatchEngine.Data.Entities.DatasetRecord", "RecordB")
                        .WithMany()
                        .HasForeignKey("RecordBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchJob");

                    b.Navigation("RecordA");

                    b.Navigation("RecordB");
                });

            modelBuilder.Entity("VectorMatchEngine.Data.Entities.Dataset", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("VectorMatchEngine.Data.Entities.MatchJob", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
